channels:
- https://packages.qiime2.org/qiime2/2024.10/amplicon/passed
- conda-forge
- bioconda
dependencies:
  - qiime2-amplicon
  - pip
  - pip:
    - q2-fmt@git+https://github.com/qiime2/q2-fmt.git@dev
    - frictionless
