{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-fmt
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    # nodejs is only necessary in the build phase - our build script needs it
    # in order to render out transpiled js assets for various visualizations.
    # once rendered, node is no longer necessary. don't set this in host reqs.
    - nodejs

  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas {{ pandas }}
    - scipy
    - scikit-bio {{ scikit_bio }}
    - jinja2
    - frictionless
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    # right now q2-stats uses a non-epoch-based version identifier - once
    # that has been addressed in q2-stats, uncomment the following line
    # - q2-stats {{ qiime2_epoch }}.*
    - q2-stats

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_fmt
    - qiime2.plugins.fmt

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
