# Example of workflow trigger for calling workflow (the client).
name: ci-dev
on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev"]
jobs:
  ci:
    uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev
    with:
      distro: amplicon
  lint: 
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q flake8
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip

    - name: Lint plugin
      shell: bash -l {0}
      run: |
        cd q2-hello-world
        flake8
        q2lint
