name: ci-q2-fmt
on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev"]
jobs:
  ci:
    uses: qiime2/distributions/.github/workflows/lib-community-ci.yaml@dev
    with:
      github-repo: q2-fmt
      env-file-name: 2024.10-q2-fmt-environment.yml
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q flake8
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip

    - name: Lint plugin
      shell: bash -l {0}
      run: |
        cd q2-hello-world
        flake8
        q2lint

